driver:
  enabled: false #this is because we are using precompiled drivers, so we don't need the GPU Operator to build and install the drivers on the nodes. By setting this to false, we can skip the driver installation process and rely on the precompiled drivers that are already available on the nodes. 
toolkit:
  enabled: true
devicePlugin:
  enabled: true
dcgmExporter:
  enabled: true
  serviceMonitor:
    enabled: true
daemonsets:
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"
    - key: kubernetes.azure.com/scalesetpriority
      operator: Equal 
      value: spot
      effect: NoSchedule
