apiVersion: v1
kind: ResourceQuota
metadata:
  name: training-quota
  namespace: vw-training
spec:
  hard:
    requests.nvidia.com/gpu: "1"
    limits.memory: 48Gi
    pods: "10"

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: serving-quota
  namespace: vw-serving
spec:
  hard: 
    requests.nvidia.com/gpu: "1"
    limits.memory: 24Gi
    pods: "15"
